trigger: none

parameters:
  - name: variableGroupName
    type: string
    default: jira-ai-project-variables-group

schedules:
  - cron: "0 4 * * SAT" # At 04:00 AM, only on Saturday
    displayName: "Weekly Saturday 4:00 AM Execution"
    branches:
      include:
        - main

variables:
  - group: jira-ai-project-variables-group

pool: Default

steps:
  - script: |
      python3.11 -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install pip dependencies"

  - script: |
      echo "Launching application..."
      python3.11 src/main.py
    displayName: "Run application"
    continueOnError: true

  - script: |
      set -e
      LOG_DIR="log/$(date +%Y)/$(date +%m)/$(date +%d)"
      if [ -d "$LOG_DIR" ]; then
        echo "Found logs in $LOG_DIR"
      else
        echo "No logs found in $LOG_DIR; creating placeholder."
        mkdir -p "$LOG_DIR"
      fi
      echo "##vso[task.setvariable variable=LOG_DIR]$LOG_DIR"
    displayName: "Detect log directory and set variable"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(LOG_DIR)
      artifact: logs-$(Build.BuildId)
      publishLocation: pipeline
    displayName: "Publish logs as pipeline artifact"

  - script: |
      set -e
      NOW_UTC="$(date -u '+%Y-%m-%d %H:%M')"
      echo "Computed end timestamp: $NOW_UTC"
      AZURE_DEVOPS_EXT_PAT="$(AIR_PIPELINE_PAT)"

      ORG="$(System.TeamFoundationCollectionUri)"
      PROJECT="$(System.TeamProject)"
      VG_NAME="${{ parameters.variableGroupName }}"
      echo "Updating variable group '$VG_NAME' in $ORG$PROJECT via Azure CLI"

      # Ensure azure-devops extension present
      if ! az extension show --name azure-devops >/dev/null 2>&1; then
        echo "Installing azure-devops CLI extension"
        az extension add --name azure-devops
      fi

      # Login using PAT (must be provided as secret variable AZURE_DEVOPS_EXT_PAT)
      if [ -z "$AZURE_DEVOPS_EXT_PAT" ]; then
        echo "ERROR: AZURE_DEVOPS_EXT_PAT not set." >&2
        exit 1
      fi
      echo "$AZURE_DEVOPS_EXT_PAT" | az devops login

      az devops configure --defaults organization="$ORG" project="$PROJECT"

      VG_ID=$(az pipelines variable-group list --query "[?name=='$VG_NAME'].id" -o tsv)
      if [ -z "$VG_ID" ]; then
        echo "ERROR: Variable group '$VG_NAME' not found." >&2
        exit 1
      fi

      echo "Found variable group id: $VG_ID"

      echo "Updating variable AIR_PIPELINE_LAST_RUN_UTC in group $VG_ID"
      az pipelines variable-group variable update \
        --group-id "$VG_ID" \
        --name AIR_PIPELINE_LAST_RUN_UTC \
        --value "$NOW_UTC" 1>/dev/null

      echo "Successfully set AIR_PIPELINE_LAST_RUN_UTC=$NOW_UTC in variable group $VG_ID"
      echo "##vso[task.setvariable variable=AIR_PIPELINE_LAST_RUN_UTC]$NOW_UTC"
    displayName: "Persist end timestamp to variable group (Azure CLI)"
    env:
      AIR_PIPELINE_PAT: $(AIR_PIPELINE_PAT)
